### ISSUE TITLE
refactor server structure to accept api endpoints

### ISSUE THREAD

**Issue by jjwon0** [altonzheng/PHC#2]
tj wrote some pretty cool boilerplate here to accept arbitrary directories and register them as endpoints, maybe we can leverage some of that code

https://github.com/koajs/api-boilerplate

**Comment by jjwon0** [comment]
nice comment on the original starter kit [here](https://github.com/davezuko/react-redux-starter-kit/issues/854) as well

**Comment by jjwon0** [comment]
alternatively we can just make a new repo for `PHC-api` and rename this one `PHC-frontend`, and use the endpoint proxying alluded to in the starter kit.

**Comment by altonzheng** [comment]
Let's use Koa, keep it simple and tidy. API should be really tiny, we want to limit network requests anyway. I'm thinking just two endpoints:

GET /account?id=xxxx
For getting additional info on an account

GET /accounts?fields=[firstname, lastname, etc.]&start=0 
For getting all accounts starting from index = start

POST /accounts -- list of accounts to post
So we can batch up queries if we want. Add a timestamp so the server can have some log for idempotent queries.

Eventually prolly want to add API for services/feedback/checkin but those will be really tiny too. what u think?

**Comment by jjwon0** [comment]
sounds good to me!  `POST /accounts` might only want to take a single account in, though.  I suck at REST though so whatever you choose I'm sure will be fine
