### ISSUE TITLE
Render the React app with accounts already populated

### ISSUE THREAD

**Issue by jjwon0** [altonzheng/PHC#51]
This way, we can cache the index of the request on the server.

**Comment by altonzheng** [comment]
what do you mean by this?

**Comment by jjwon0** [comment]
I feel like we should be able to just perform the bulk query result once and save the result in-memory, and pass it to the front-end somehow such that `window.accounts` is pre-populated.

**Comment by jjwon0** [comment]
Search is server-side now, so this doesn't matter.
