### ISSUE TITLE
add a simple grid

### ISSUE THREAD

**Issue by jjwon0** [altonzheng/PHC#7]
will make prettifying this thing a lot easier

can either use something in postcss like [lost-grid](https://github.com/peterramsing/lost) or something in scss like [neat](http://neat.bourbon.io/)

**Comment by altonzheng** [comment]
Can you look into this? I suck at css lol idk whats good

**Comment by jjwon0** [comment]
added lostgrid which looks dope, closed in cce04986e6f1b288de7b2b5f6e41e10a56bbc688
