### ISSUE TITLE
add flow

### ISSUE THREAD

**Issue by jjwon0** [altonzheng/PHC#9]
if we're feeling particularly ambitious......................

**Comment by altonzheng** [comment]
Aren't we already using Flow? 🐙

**Comment by jjwon0** [comment]
I only see Flow in the Zen stuff haha.

**Comment by jjwon0** [comment]
not a good decision

- starting to think flow is bad; despite it being a good technology, it's losing to typescript hard
- we don't have anything here complicated enough for it to really matter a lot
- will take a lot of time that we don't really have
- makes the code harder to pick up and understand for a new developer
