### ISSUE TITLE
remove abstraction over salesforce for some objects

### ISSUE THREAD

**Issue by jjwon0** [altonzheng/PHC#93]
in order for this to become self service, we can't have this api wrapper, because if phc ever wants to update things (e.g. services), they should be able to update in salesforce and see in app; this means app needs to understand salesforce

**Comment by jjwon0** [comment]
updated to specify that this is for only some objects, b/c in the account, there is logic that is better kept the same (e.g. other language, other ethnicity fields)

**Comment by altonzheng** [comment]
can't the app just pull the services from salesforce? or do you mean if the change the schema of the objects

**Comment by jjwon0** [comment]
yeah i meant this as in the salesforce services, but realized later that the services aren't even separate objects in the db (they're hardcoded attrs of the `PHC_Event__c`) so this is kind of a moot issue until the formerly mentioned problem is fixed
